UPDATE "JobCategory" AS category
SET "sortOrder" = catalog."sortOrder"
FROM (VALUES
  ('cleaning', 1),
  ('janitor', 2),
  ('customer_service', 3),
  ('security', 7),
  ('warehouse', 8),
  ('administration', 15)
) AS catalog("id", "sortOrder")
WHERE category."id" = catalog."id";

INSERT INTO "JobCategory" ("id", "name", "icon", "sortOrder", "isActive")
VALUES
  ('hospitality_food', 'Restaurantes, hotelería y turismo', 'restaurant', 4, true),
  ('health_care', 'Salud y cuidado', 'medical', 5, true),
  ('personal_care', 'Belleza y cuidado personal', 'beauty', 6, true),
  ('transport_delivery', 'Transporte y reparto', 'truck', 9, true),
  ('manufacturing', 'Producción y manufactura', 'factory', 10, true),
  ('agriculture_livestock', 'Agricultura y ganadería', 'agriculture', 11, true),
  ('construction_trades', 'Construcción y oficios', 'hard_hat', 12, true),
  ('automotive_service', 'Mecánica y servicio automotriz', 'car', 13, true),
  ('technology_it', 'Tecnología y soporte', 'laptop', 14, true),
  ('education_training', 'Educación y capacitación', 'school', 16, true)
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "icon" = EXCLUDED."icon",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = EXCLUDED."isActive";

INSERT INTO "JobSpecialty" ("id", "categoryId", "name", "sortOrder", "isActive")
VALUES
  ('hospitality_cook', 'hospitality_food', 'Cocinero/a', 1, true),
  ('hospitality_kitchen_assistant', 'hospitality_food', 'Ayudante de cocina', 2, true),
  ('hospitality_waiter', 'hospitality_food', 'Mesero/a', 3, true),
  ('hospitality_barista', 'hospitality_food', 'Barista', 4, true),
  ('hospitality_bartender', 'hospitality_food', 'Bartender', 5, true),
  ('hospitality_dishwasher', 'hospitality_food', 'Lavaplatos', 6, true),
  ('hospitality_hotel_reception', 'hospitality_food', 'Recepcionista de hotel', 7, true),
  ('hospitality_room_attendant', 'hospitality_food', 'Camarista y limpieza de habitaciones', 8, true),
  ('hospitality_tour_guide', 'hospitality_food', 'Guía turístico/a', 9, true),
  ('health_nurse', 'health_care', 'Enfermería', 1, true),
  ('health_nursing_assistant', 'health_care', 'Auxiliar de enfermería', 2, true),
  ('health_clinical_assistant', 'health_care', 'Asistente clínico', 3, true),
  ('health_dental_assistant', 'health_care', 'Asistente dental', 4, true),
  ('health_pharmacy_assistant', 'health_care', 'Auxiliar de farmacia', 5, true),
  ('health_clinic_reception', 'health_care', 'Recepción de clínica', 6, true),
  ('health_lab_technician', 'health_care', 'Técnico/a de laboratorio', 7, true),
  ('health_phlebotomy', 'health_care', 'Toma de muestras', 8, true),
  ('personal_stylist', 'personal_care', 'Estilista', 1, true),
  ('personal_barber', 'personal_care', 'Barbería', 2, true),
  ('personal_nails', 'personal_care', 'Manicure y pedicure', 3, true),
  ('personal_makeup', 'personal_care', 'Maquillaje', 4, true),
  ('personal_cosmetology', 'personal_care', 'Cosmetología', 5, true),
  ('personal_massage', 'personal_care', 'Masajes', 6, true),
  ('personal_skin_care', 'personal_care', 'Cuidado de la piel', 7, true),
  ('transport_delivery', 'transport_delivery', 'Repartidor/a', 1, true),
  ('transport_motorcycle', 'transport_delivery', 'Motorizado/a', 2, true),
  ('transport_private_driver', 'transport_delivery', 'Chofer particular', 3, true),
  ('transport_taxi', 'transport_delivery', 'Taxista', 4, true),
  ('transport_bus', 'transport_delivery', 'Conductor/a de autobús', 5, true),
  ('transport_truck', 'transport_delivery', 'Conductor/a de camión', 6, true),
  ('transport_courier', 'transport_delivery', 'Mensajería', 7, true),
  ('transport_dispatch', 'transport_delivery', 'Despacho y rutas', 8, true),
  ('production_line', 'manufacturing', 'Operario/a de producción', 1, true),
  ('production_packaging', 'manufacturing', 'Empaque y etiquetado', 2, true),
  ('production_machine', 'manufacturing', 'Operador/a de maquinaria', 3, true),
  ('production_assembly', 'manufacturing', 'Ensamblaje', 4, true),
  ('production_quality_control', 'manufacturing', 'Control de calidad', 5, true),
  ('production_sewing', 'manufacturing', 'Costura y confección', 6, true),
  ('production_food_processing', 'manufacturing', 'Procesamiento de alimentos', 7, true),
  ('production_supervisor', 'manufacturing', 'Supervisión de línea', 8, true),
  ('agriculture_crop_worker', 'agriculture_livestock', 'Siembra y cultivo', 1, true),
  ('agriculture_coffee_harvest', 'agriculture_livestock', 'Corte de café y cosecha', 2, true),
  ('agriculture_livestock_care', 'agriculture_livestock', 'Manejo de ganado', 3, true),
  ('agriculture_milking', 'agriculture_livestock', 'Ordeño', 4, true),
  ('agriculture_poultry', 'agriculture_livestock', 'Avicultura', 5, true),
  ('agriculture_irrigation', 'agriculture_livestock', 'Riego de cultivos', 6, true),
  ('agriculture_machinery', 'agriculture_livestock', 'Maquinaria agrícola', 7, true),
  ('agriculture_greenhouse', 'agriculture_livestock', 'Viveros e invernaderos', 8, true),
  ('construction_helper', 'construction_trades', 'Ayudante de construcción', 1, true),
  ('construction_masonry', 'construction_trades', 'Albañilería', 2, true),
  ('construction_carpentry', 'construction_trades', 'Carpintería', 3, true),
  ('construction_plumbing', 'construction_trades', 'Fontanería', 4, true),
  ('construction_electrical', 'construction_trades', 'Electricidad', 5, true),
  ('construction_welding', 'construction_trades', 'Soldadura', 6, true),
  ('construction_painting', 'construction_trades', 'Pintura', 7, true),
  ('construction_drywall', 'construction_trades', 'Gypsum y tabla roca', 8, true),
  ('construction_tiling', 'construction_trades', 'Cerámica y acabados', 9, true),
  ('construction_roofing', 'construction_trades', 'Techado y cubiertas', 10, true),
  ('auto_mechanic', 'automotive_service', 'Mecánica automotriz', 1, true),
  ('auto_motorcycle_mechanic', 'automotive_service', 'Mecánica de motocicletas', 2, true),
  ('auto_tire_service', 'automotive_service', 'Llantería', 3, true),
  ('auto_electrical', 'automotive_service', 'Electricidad automotriz', 4, true),
  ('auto_bodywork', 'automotive_service', 'Enderezado y pintura', 5, true),
  ('auto_oil_change', 'automotive_service', 'Cambio de aceite y lubricación', 6, true),
  ('auto_diagnostics', 'automotive_service', 'Diagnóstico automotriz', 7, true),
  ('tech_support', 'technology_it', 'Soporte técnico', 1, true),
  ('tech_computer_repair', 'technology_it', 'Reparación de computadoras', 2, true),
  ('tech_networks', 'technology_it', 'Redes y conectividad', 3, true),
  ('tech_systems_admin', 'technology_it', 'Administración de sistemas', 4, true),
  ('tech_web_development', 'technology_it', 'Desarrollo web', 5, true),
  ('tech_software_development', 'technology_it', 'Desarrollo de software', 6, true),
  ('tech_data_analysis', 'technology_it', 'Análisis de datos', 7, true),
  ('tech_cybersecurity', 'technology_it', 'Ciberseguridad', 8, true),
  ('education_preschool', 'education_training', 'Docencia preescolar', 1, true),
  ('education_primary', 'education_training', 'Docencia primaria', 2, true),
  ('education_secondary', 'education_training', 'Docencia secundaria', 3, true),
  ('education_classroom_assistant', 'education_training', 'Asistente de aula', 4, true),
  ('education_tutoring', 'education_training', 'Tutorías', 5, true),
  ('education_language_instructor', 'education_training', 'Enseñanza de idiomas', 6, true),
  ('education_vocational_instructor', 'education_training', 'Instructor/a técnico/a', 7, true)
ON CONFLICT ("id") DO UPDATE SET
  "categoryId" = EXCLUDED."categoryId",
  "name" = EXCLUDED."name",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = EXCLUDED."isActive";
