export const NICARAGUA_DEPARTMENTS = [
  'Boaco',
  'Carazo',
  'Chinandega',
  'Chontales',
  'Estelí',
  'Granada',
  'Jinotega',
  'León',
  'Madriz',
  'Managua',
  'Masaya',
  'Matagalpa',
  'Nueva Segovia',
  'Región Autónoma de la Costa Caribe Norte',
  'Región Autónoma de la Costa Caribe Sur',
  'Río San Juan',
  'Rivas',
] as const;
